# -*- coding: utf-8 -*-
"""02md.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQdi8O0g18X58OtfTSdZKt1y8_uU5xEg
"""

nilai = int(input('Masukkan Nilai = '))
if nilai >= 90:
  print ('A')
elif nilai >= 80 and nilai <= 89:
  print('B')
elif nilai >= 70 and nilai <= 79:
  print('C')
elif nilai >= 60 and nilai <= 69:
  print('D')
elif nilai <= 59:
  print('E')

nilai = int(input('Masukkan Nilai = '))
if nilai >= 90:
  print ('A')
elif nilai >= 80 and nilai <= 89:
  print('B')
elif nilai >= 70 and nilai <= 79:
  print('C')
elif nilai >= 60 and nilai <= 69:
  print('D')
elif nilai <= 59:
  print('E')