# -*- coding: utf-8 -*-
"""03md.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a0OFmjneREafCZI8Yb52EJypcs-OsNNr
"""

inputan = int(input('Silahkan memasukkan angka yang akan di cek = '))
if inputan % 2 == 0:
  print(inputan, 'adalah genap')
else:
  print(inputan, 'adalah ganjil')

inputan = int(input('Silahkan memasukkan angka yang akan di cek = '))
if inputan % 2 == 0:
  print(inputan, 'adalah genap')
else:
  print(inputan, 'adalah ganjil')