# -*- coding: utf-8 -*-
"""05md.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17t0RmNsDa4A-CRJ9DV6Z54je-zmSoa3T
"""

usia = int(input('Masukkan Usia Penonton = '))
if usia >= 21:
  print ('Rating film adalag DEWASA')
elif usia >= 13:
  print('Rating film adalah REMAJA')
elif usia >= 9:
  print('Rating film adalah BIMBINGAN ORANG TUA')
elif nilai < 9:
  print('Rating film adalah SEMUA USIA')

usia = int(input('Masukkan Usia Penonton = '))
if usia >= 21:
  print ('Rating film adalag DEWASA')
elif usia >= 13:
  print('Rating film adalah REMAJA')
elif usia >= 9:
  print('Rating film adalah BIMBINGAN ORANG TUA')
elif nilai < 9:
  print('Rating film adalah SEMUA USIA')